# Generated by Django 5.2 on 2025-05-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='duration',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
