# Generated by Django 5.2.3 on 2025-06-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0004_userproject_role_alter_userproject_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationTimesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timesheet_number', models.IntegerField()),
                ('month', models.DateField(choices=[('JAN', 'January'), ('FEB', 'February'), ('MAR', 'March'), ('APR', 'April'), ('MAY', 'May'), ('JUN', 'June'), ('JUL', 'July'), ('AUG', 'August'), ('SEP', 'September'), ('OCT', 'October'), ('NOV', 'November'), ('DEC', 'December')], default='JAN', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=20)),
                ('result', models.JSONField()),
                ('type', models.CharField(choices=[('BULK', 'Bulk Upload Validation'), ('AUTO', 'Automated Validation'), ('ROW', 'Individual Row Validation')], default='AUTO', max_length=10)),
            ],
            options={
                'db_table': 'automation_timesheet',
            },
        ),
    ]
