# Generated by Django 5.2.3 on 2025-07-03 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0007_remove_automationtimesheet_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='automationtimesheet',
            name='type',
            field=models.CharField(choices=[('UPLOAD', 'Upload Validation'), ('AUTO', 'Automated Validation'), ('MANUAL', 'Manual Validation')], default='AUTO', max_length=10),
        ),
    ]
