# Generated by Django 5.2.3 on 2025-07-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0009_alter_timesheet_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationtimesheet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
