# Generated by Django 4.2 on 2026-07-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0018_notification_leaverequest_activitylog_leavebalance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='attendance_status',
            field=models.CharField(choices=[('Present', 'Present'), ('Half Day', 'Half Day'), ('Absent', 'Absent')], default='Absent', max_length=20),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='punch_in_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='punch_in_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='punch_out_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='punch_out_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
