# Generated by Django 4.2 on 2026-07-14 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0019_attendancelog_attendance_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancelog',
            name='break_end',
        ),
        migrations.RemoveField(
            model_name='attendancelog',
            name='break_start',
        ),
    ]
