# Generated by Django 4.2 on 2026-07-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0020_remove_attendancelog_break_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='punch_in_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='punch_out_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
