# Generated by Django 5.2 on 2025-05-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_alter_timesheet_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='task_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
