# Generated by Django 5.2 on 2025-06-01 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_alter_timesheet_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproject',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('collaborator', 'Collaborator')], default='collaborator', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='userproject',
            unique_together={('user', 'project')},
        ),
    ]
