# Generated by Django 5.2.3 on 2025-06-30 10:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0005_automationtimesheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationtimesheet',
            name='year',
            field=models.IntegerField(default=2025, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2026)]),
        ),
    ]
