# Generated by Django 5.2.3 on 2025-07-01 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0006_automationtimesheet_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automationtimesheet',
            name='year',
        ),
    ]
