# Generated by Django 5.2.3 on 2025-07-03 05:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0008_timesheet_updated_at_alter_automationtimesheet_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
